### ISSUE TITLE
Tracker for upgrading to LangChain4j 0.32

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#700]
Checklist:

- [x] Switch the parallel execution of in-process embedding models to use the quarkus worker pool (see https://github.com/langchain4j/langchain4j-embeddings/pull/31) - IMPLEMENTED IN https://github.com/jmartisk/quarkus-langchain4j/commit/74fd385163d84e042be392da25afc74b1ab15cf3
- [x] Breaking changes in Mistral models due to https://github.com/langchain4j/langchain4j/pull/1226 
 - [x] Use new observability interfaces (see https://github.com/langchain4j/langchain4j/pull/1229)

**Comment by jmartisk** [comment]
@geoand let's try tracking the necessary changes like this, WDYT?
Once we become aware of more, we can add them here

**Comment by geoand** [comment]
Sounds like a good idea!

**Comment by jmartisk** [comment]
I've also pushed a branch https://github.com/quarkiverse/quarkus-langchain4j/tree/langchain4j-0.32 that integrates the mandatory changes for the upgrade. I've been doing this for SmallRye GraphQL for quite a while, maintaining an upgrade branch over time, rather than implementing everything at once the new version is released... Let's see how it works... We can always back off

**Comment by geoand** [comment]
Sure, let's see how it goes

**Comment by geoand** [comment]
@jmartisk I assume you haven't done anything for MistralAI, correct? 

Asking so I don't duplicate work

**Comment by jmartisk** [comment]
Correct, I haven't looked at that

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
I have force pushed an update
